<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ris="http://www.ivoa.net/wsdl/RegistrySearch/v1.0" name="searchableRegistry" targetNamespace="http://www.ivoa.net/wsdl/RegistrySearch">
<import namespace="http://www.ivoa.net/wsdl/RegistrySearch/v1.0" location="http://localhost:8080/registry/schema/registry/RegistrySearch/v1.0/Search.wsdl"></import>
<xs:import namespace="http://www.ivoa.net/xml/RegistryInterface/v1.0" schemaLocation="http://localhost:8080/registry/schema/registry/RegistryInterface/v1.0/RegistryInterface.xsd"></xs:import>
<xs:import namespace="http://www.ivoa.net/xml/VOResource/v1.0" schemaLocation="http://localhost:8080/registry/schema/vo-resource-types/VOResource/v1.0/VOResource.xsd"></xs:import>
<xs:import namespace="http://www.ivoa.net/xml/ADQL/v1.0" schemaLocation="http://localhost:8080/registry/schema/adql/ADQL/v1.0/ADQL.xsd"></xs:import>
<xs:import namespace="http://www.ivoa.net/xml/VORegistry/v1.0" schemaLocation="http://localhost:8080/registry/schema/vo-resource-types/VORegistry/v1.0/VORegistry.xsd"></xs:import>
<xs:import namespace="http://www.ivoa.net/xml/ConeSearch/v1.0" schemaLocation="http://localhost:8080/registry/schema/vo-resource-types/ConeSearch/v1.0/ConeSearch.xsd"></xs:import>
<xs:import namespace="http://www.ivoa.net/xml/SIA/v1.0" schemaLocation="http://localhost:8080/registry/schema/vo-resource-types/SIA/v1.0/SIA.xsd"></xs:import>
<xs:import namespace="http://www.ivoa.net/xml/VODataService/v1.0" schemaLocation="http://localhost:8080/registry/schema/vo-resource-types/VODataService/v1.0/VODataService.xsd"></xs:import>
<xs:import namespace="http://www.ivoa.net/xml/VOApplication/v1.0rc1" schemaLocation="http://localhost:8080/registry/schema/vo-resource-types/VOApplication/v1.0rc1/VOApplication.xsd"></xs:import>
<xs:import namespace="http://www.ivoa.net/xml/VOStandard/v0.1" schemaLocation="http://localhost:8080/registry/schema/vo-resource-types/VOStandard/v0.1/VOStandard.xsd"></xs:import>
<service name="RegistryInterfaceService">
<port name="RegistrySearchPort" binding="ris:RegistrySearchSOAP">
<soap:address location="http://localhost:8080/registry/services/RegistryQueryv1_0"></soap:address>
</port>
</service>
</definitions>